# Generated by Django 2.2 on 2020-10-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200928_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(default=200),
        ),
    ]
