# Generated by Django 2.2 on 2020-10-13 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_item_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='favourite',
        ),
        migrations.AddField(
            model_name='item',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
