# Generated by Django 2.2 on 2020-10-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201013_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'MAC'), ('SW', 'MAC PRO'), ('OW', 'IPHONE')], max_length=2, null=True),
        ),
    ]
