# Generated by Django 2.2 on 2020-10-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201015_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='subcat', max_length=100, unique=True),
        ),
    ]
