# Generated by Django 2.2 on 2020-10-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201015_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='brand1',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
        ),
    ]
