# Generated by Django 2.2 on 2020-10-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofileoption',
            name='user',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfileOption',
        ),
    ]
