# Generated by Django 2.2 on 2020-10-19 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_profile', '0003_sellerprofilecreateadmin_sellerprofileforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofileforuser',
            name='seller_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller_profile.SellerProfileCreateAdmin'),
        ),
    ]
